#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2014-05-26  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 port-pathname maintainer\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

if ! which bmake; then
    printf "Error: bmake not found in PATH.\n"
    exit 1
fi

port_path=$1
maintainer=$2

if [ ! -e $port_path ]; then
    printf "$port_path does not exist.\n"
    exit 1
fi

if [ `uname` = NetBSD ]; then
    make=make
else
    make=bmake
fi

port_name=`basename $1`

if [ -d $port_name ]; then
    printf "$port_name already exists.  Overwrite? (y/[n]) "
    read overwrite
    if [ 0$overwrite = 0y ]; then
	rm -rf $port_name
	new_pkg=1
    else
	new_pkg=0
    fi
else
    new_pkg=1
fi

if [ $new_pkg = 1 ]; then
    mkdir $port_name
    cd $port_name
    
    ##########################################################################
    #   Copy over basic file structure
    ##########################################################################
    
    cp $port_path/pkg-descr DESCR
    chmod 644 DESCR
    if [ -e $port_path/files ]; then
	cp -R $port_path/files .
	
	# Remove old subversion files if present
	rm -rf files/.svn
	
	mkdir -p patches
	if ! mv files/patch-* patches; then
	    printf "No patch files moved.\n"
	else
	    # Add $NetBSD$ tag to each patch as required by pkglint
	    for file in patches/patch-*; do
		printf '%s\n\n' '$NetBSD$' > $file.temp
		cat $file >> $file.temp
		mv $file.temp $file
	    done
	fi
    
	for dir in files patches; do
	    if [ 0`ls -A $dir` = 0 ]; then
		rmdir $dir
	    fi
	done
    fi
    
    ##########################################################################
    #   Convert Makefile
    ##########################################################################
    
    awk -v maintainer=$maintainer -f ~/scripts/fbsd2pkg.awk \
	$port_path/Makefile > Makefile
    createbuildlink > buildlink3.mk
    printf '@comment $NetBSD$\n' > PLIST
else
    cd $port_name
fi

if [ 0$EDITOR = 0 ]; then
    EDITOR=vi
fi

$EDITOR Makefile
$EDITOR buildlink3.mk
$make deinstall
$make clean
$make makesum
$make makepatchsum
$make patch
$make
$make install
if [ `uname` != Darwin ]; then
    $make print-PLIST > PLIST
    $make clean
    $make deinstall
    $make install
else
    cat << EOM

================================================================
Skipping print-PLIST because Darwin uses .dylib instead of .so.
================================================================

EOM
fi
$make deinstall
$make clean
pkglint

